package vn.edu.eaut.lab3;
import javax.swing.*;import javax.swing.table.DefaultTableModel;import java.awt.*;
@SuppressWarnings("unused")
public class Bai08QuanLySinhVien extends JFrame{
 private static final long serialVersionUID = 1L;
 JTextField ma=new JTextField(),ten=new JTextField(),diem=new JTextField();DefaultTableModel model;JTable table;
 public Bai08QuanLySinhVien(){setTitle("Bài 8 - Quản lý sinh viên");setDefaultCloseOperation(EXIT_ON_CLOSE);setLayout(new BorderLayout(8,8));JPanel f=new JPanel(new GridLayout(3,2));f.add(new JLabel("Mã sinh viên:"));f.add(ma);f.add(new JLabel("Họ tên:"));f.add(ten);f.add(new JLabel("Điểm trung bình:"));f.add(diem);JPanel b=new JPanel();for(String s:new String[]{"Thêm","Sửa","Xóa","Làm mới"}){JButton bt=new JButton(s);bt.addActionListener(e->action(s));b.add(bt);}model=new DefaultTableModel(new String[]{"Mã SV","Họ tên","Điểm TB","Xếp loại"},0);table=new JTable(model);table.getSelectionModel().addListSelectionListener(e->{int r=table.getSelectedRow();if(r>=0){ma.setText(model.getValueAt(r,0).toString());ten.setText(model.getValueAt(r,1).toString());diem.setText(model.getValueAt(r,2).toString());}});add(f,BorderLayout.NORTH);add(new JScrollPane(table),BorderLayout.CENTER);add(b,BorderLayout.SOUTH);setSize(650,450);setLocationRelativeTo(null);}
 void action(String s){if(s.equals("Làm mới")){ma.setText("");ten.setText("");diem.setText("");return;}if(s.equals("Xóa")){int r=table.getSelectedRow();if(r>=0)model.removeRow(r);else JOptionPane.showMessageDialog(this,"Hãy chọn sinh viên!");return;}try{String m=ma.getText().trim(),h=ten.getText().trim();double d=Double.parseDouble(diem.getText());if(m.isEmpty()||h.isEmpty()||d<0||d>10)throw new Exception("Dữ liệu không hợp lệ!");Student st=new Student(m,h,d);if(s.equals("Thêm"))model.addRow(new Object[]{m,h,d,st.xepLoai()});else{int r=table.getSelectedRow();if(r<0)throw new Exception("Hãy chọn sinh viên!");model.setValueAt(m,r,0);model.setValueAt(h,r,1);model.setValueAt(d,r,2);model.setValueAt(st.xepLoai(),r,3);}}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
 public static void main(String[]x){SwingUtilities.invokeLater(()->new Bai08QuanLySinhVien().setVisible(true));}}
